# Generated by Django 5.0.6 on 2024-05-14 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contabilidad', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credito', models.PositiveIntegerField()),
                ('num_cuotas', models.SmallIntegerField()),
                ('monto_cuotas', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField()),
                ('proximo_pago', models.DateField()),
                ('estado', models.CharField(choices=[('al día', 'Al Día'), ('en mora', 'En Mora'), ('cancelado', 'Cancelado')], max_length=15)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditos', to='Ventas.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.PositiveIntegerField()),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagos', to='Cobranza.creditos')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagos', to='Contabilidad.transacciones')),
            ],
        ),
    ]
