# Generated by Django 5.0.6 on 2024-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('salario', models.PositiveIntegerField()),
            ],
        ),
    ]
