# Generated by Django 5.0.6 on 2024-08-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasdetalle',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
