# Generated by Django 5.0.6 on 2024-08-21 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasdetalle',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='comprasdetalle',
            name='producto',
        ),
        migrations.RenameField(
            model_name='historicalproductos',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='nombre',
            new_name='nombre_proveedor',
        ),
        migrations.RemoveField(
            model_name='historicalproductos',
            name='dimensiones',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='dimensiones',
        ),
        migrations.AddField(
            model_name='historicalproductos',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Inventario.proveedores'),
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='Producto', to='Inventario.proveedores'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='ComprasDetalle',
        ),
    ]
